### ISSUE TITLE
Licensing policy 

### ISSUE THREAD

**Issue by skovtunenko** [go101/go101#12]
Hello!
First of all thank you for sharing this. This material of exceptional quality.

I'm also maintain my own (_still publicity unavailable_) short abstract (_for personal needs only, not for sale_) and want to borrow some quotes from your work (of course with references to original source).

Is it possible?

**Comment by go101** [comment]
short answer: absolutely no problem.

The license will be modified soon. The basic principle is, for online-repost, a link back is required, for print publish versions, there would be more requirements.

**Comment by go101** [comment]
This issue to be closed. You can still add comments if there are questions.
