### ISSUE TITLE
Article about closing channels

### ISSUE THREAD

**Issue by leolara** [go101/go101#132]
Inspired by your article https://go101.org/article/channel-closing.html , I wrote this one  https://dev.to/leolara/closing-a-go-channel-written-by-several-goroutines-52j2

I wanted to let you know

**Comment by leolara** [comment]
Thanks for answering, this is very interesting!! I show it to some people but this the most interesting answer by far. Thanks!!

Minor issues:

1. I didn't know that chan struct{} uses less memory, that is something I will take into account from now on
2. The issue that calling Close more than once is a bug is clear, I thought that for the purposes of this exercise was a secondary thing and talking about that was complicating things. Anyway, I will add a not
3. Regarding your point of creating a goroutine for each write is more inefficient, I do not know, I think most Go webservers spin a goroutine for each client request, for example. Anyway, the article is meant as an exercise of closing a channel written by several goroutines so this is necessary, even if for a specific situation other alternative is more efficient.

What it is very interesting for me is what you raise about another race condition.

I do not see it, although I might not understand.

What I think you are saying is that if a write goroutine is scheduled out between the selects, then when `close(p.ch)` is closed the second select can panic. What I think in that case is that: `close(p.ch)` will not be called until `Wait` unlocks. To Wait unlock that write goroutine has to exit triggering the `Done` and hence that situation does not happen.

**Comment by leolara** [comment]
If you mean that a write goroutine wakes up after the first select, while the close is already pass the Wait, that is not possible as `close(p.closingCh)` is executed before the lock, and hence, any `write` that is pass the first select, has had to enter before `Wait` is called.

**Comment by leolara** [comment]
It is very interesting your code.

In my article I was trying to solve the generic problem of "closing a channel with several goroutines writing", and I think in your solution only has one goroutine writing, so it is a different problem. My code was simply a example situation to have generate the problem of closing a channel with several writers.

Anyway, it would be very interesting to benchmark both solutions. If I find time I will try to do it.

**Comment by go101** [comment]
I modified the code to use rog's clever idea shown in [this thread](https://groups.google.com/forum/#!msg/golang-nuts/lEKehHH7kZY/SRmCtXDZAAAJ) instead of `sync.Once` to implement the Close method.

And here is [a simpler version](https://play.golang.org/p/dAppUxP96g4) you may have read it.

**Comment by go101** [comment]
I modified the `run` method in the simpler version, so that the last possible successfully sent value [will never be lost](https://play.golang.org/p/nxCLgrKKJ8f).

**Comment by go101** [comment]
I decided to close this issue now.
