### ISSUE TITLE
About  "How to Gracefully Close Channels" confused.

### ISSUE THREAD

**Issue by sigma65535** [go101/go101#133]
I am sorry for my english is poor.
The problem is :
 I add a line code  to send 1 to chan ,and the function output is error:
  as follow:

```
package main

import "fmt"

type T int

func IsClosed(ch <-chan T) bool {
	select {
	case <-ch:
		return true
	default:
	}

	return false
}

func main() {
	c := make(chan T,1)
	c <-1  // **i add code in here**
	fmt.Println(IsClosed(c)) // false
	close(c)
	fmt.Println(IsClosed(c)) // true
}
```

the ouput is :
true
true

**Comment by go101** [comment]
There is a condition to use the function:
> ... if you can make sure no values were (and will be) ever sent to the channel

**Comment by sigma65535** [comment]
Sorry,I did't notice that,thank u
