### ISSUE TITLE
RFE: Update build process to tag released ebooks with release version

### ISSUE THREAD

**Issue by atc0005** [go101/go101#135]
Currently the releases appear to lack that information.

**Comment by go101** [comment]
I don't understand your request. Could you describe it in more detail?

**Comment by atc0005** [comment]
> I don't understand your request. Could you describe it in more detail?

Sure thing. 

When provided, the release version or edition is usually provided in one of two (maybe three) places. Here are a few examples I pulled from some various Go books I've purchased:

- Front of the book near the copyright/printing/ISBN information
  - e.g., `Second printing, December 2015`
  - e.g., `Revision History for the First Edition`
    - `2016-01-06: First Release`
  - e.g., `This version was published on YYYY-MM-DD`

Here are some examples pulled from The Kubernetes Book and The Docker Book:

- Dedicated section in the first chapter
  - e.g., `Versions of the book` (*this is the chapter name*)
  - e.g., `Version` (*this is the chapter name*)
    - `This is version v18.09 (6172afc) of The Docker Book`

**Comment by go101** [comment]
OK, I get it. Thanks for the improvement request.

Currently, the ebooks are built by another program: https://github.com/go101/go101-ebooks
and for programming simplicity, the versions are put in filenames only.

I will lean how to draw the versions on the cover image in Go and improve the process.

**Comment by atc0005** [comment]
> OK, I get it. Thanks for the improvement request.

Thank *you* for providing the book. I've not gotten far into it (still working through some other material and test projects), but where I have spot checked it looks to have a lot of good coverage that will help me in my studies. I hope I'll learn enough to be able to contribute at some point.

> Currently, the ebooks are built by another program: https://github.com/go101/go101-ebooks

I wasn't aware of that repo, I'll take a look to see what I can learn from the code. I see that you've already noted it's not of a quality to use as a measurement for best practices, but I suspect it still has a lot of good ideas to learn from.

Thanks for considering this enhancement request. :)

**Comment by go101** [comment]
@atc0005 Thanks for the great suggestion. It is implemented now. So I close it.
