### ISSUE TITLE
starting local server

### ISSUE THREAD

**Issue by lanastasov** [go101/go101#136]
`go run main.go`
.\main.go:29:8: undefined: openBrowser
.\main.go:34:5: undefined: go101

`go run *.go`
CreateFile *.go: The filename, directory name, or volume label syntax is incorrect.

go version go1.12.4 windows/amd64

what might be the problem?

**Comment by go101** [comment]
It works okay for me (on Linux).
What's the OS you are using? 

What does the following command output?
```
echo *.go
```

For me, it outputs:
```
go101.go go-get.go main.go
```

**Comment by go101** [comment]
Could you check if `go run .` works?

**Comment by lanastasov** [comment]
Yes, it does work. Thanks.

**Comment by go101** [comment]
Thanks for this finding and the help for the checking!
