### ISSUE TITLE
Found an error in chart 48

### ISSUE THREAD

**Issue by GFZRZK** [go101/go101#139]
The version of the book is Golang101-v1.13.j.pdf-SongTi, I found 
![image](https://user-images.githubusercontent.com/34792731/69819440-fc16a600-1239-11ea-859d-5a04c3585727.png),but in my env, it can be run successfully when only _z==z
![image](https://user-images.githubusercontent.com/34792731/69819583-33855280-123a-11ea-91b6-4e2eeadef567.png)
My go compile is from offical so I think maybe there is something wrong in the book?

**Comment by go101** [comment]
Many thanks for this finding.

It is some weird, I should have checked all examples in the book.
But there are still several errors in it. I'm very sorry for that.
