### ISSUE TITLE
panic-and-recover

### ISSUE THREAD

**Issue by Bububuger** [go101/go101#143]
hi, go101 is very helpful for me. 👍 

but when reading [panic-and-recover of go101](https://go101.org/article/panic-and-recover-more.html#exiting-phase), i found someting wrong in the last example :
```go
// This program exits without panic 1 being recovered.
package main

func demo() {
	defer func() {
		defer func() {
			recover() // this one recovers panic 2
		}()

		defer recover() // no-op

		panic(2)
	}()
	panic(1)
}

func main() {
	demo()
}
```
it says
>  In fact, the current Go specification also doesn't explain well why the second recover call, which is expected to recover panic 1, in the following example doesn't take effect.

and

> What Go specification doesn't mention is that, at any given time, only the newest unrecovered panic in a goroutine is recoverable. In other words, each recover call is viewed as an attempt to recover the newest unrecovered panic in the currrent goroutine. This is why the second recover call in the above example is a no-op.

i do not think so.
the current verson of Go specification says : 
> The return value of recover is nil if any of the following conditions holds:
> 1. panic's argument was nil;
> 2. the goroutine is not panicking;
> 3. recover was not called directly by a deferred function.

the third condition that is the reason why the second recover call, which is expected to recover panic 1, in the following example doesn't take effect.

then i found something interesting:

example 1 ：
```go
// This program exits without panic 1 being recovered.
package main

func demo() {
	defer func() {
		defer func() {
			recover() // this one recovers panic 2
		}()

		defer recover() // no-op

		panic(2)
	}()
	panic(1)
}

func main() {
	demo()
}
```

example 2 ：
```go
// This program exits with no panic.
package main

func demo() {
	defer func() {
		defer func() {
			recover() // this one recovers panic 2
		}()

		defer fmt.Println(recover()) // this one recover panic 1

		panic(2)
	}()
	panic(1)
}

func main() {
	demo()
}
```

example 3 ：
```go
// This program exits without panic 1 being recovered.
package main

func demo() {
	defer func() {
		defer func() {
			recover() // this one recovers panic 2
		}()

		defer func() {
			fmt.Println(recover()) //no-ops
		}()

		panic(2)
	}()
	panic(1)
}

func main() {
	demo()
}
```

now i know the reason why example 1  exit whit panic , but i don't know why example 2 and example 3  play different.

**Comment by go101** [comment]
> the third condition that is the reason why the second recover call, which is expected to recover panic 1, in the following example doesn't take effect.

The third condition is **_recover was not called directly by a deferred function._**, whereas the call `defer recover()` is exactly called directly by a deferred function.

In your example 3, the call `recover()`, as the argument of `fmt.Println(...)`, is executed/evaluated before executing `panic(2)`. That is why it recovers panic 1.

The comments in your example 3 is not correct, the "no-ops" and "this one recovers panic 2" should be exchanged.

**Comment by Bububuger** [comment]
Thanks for answering, i'm sorry for replying too late.
I basically agree with what you said, except for one point:
>The third condition is recover was not called directly by a deferred function., whereas the call defer recover() is exactly called directly by a deferred function defer func() {...}.

if `whereas the call defer recover() is exactly called directly by a deferred function defer func() {...}` how to explain the follow example:

```go
// This program exits with no panic being recovered.
package main

func demo() {
	defer func() {
		defer recover() //no-ops
		defer recover() //no-ops

		panic(2)
	}()
	panic(1)
}

func main() {
	demo()
}
```

and another one interesting point is :
>when a func call with arguments called directly by a defer statement, arguments  are executed/evaluated when defer statement is declared not in the exiting phases.

```go
package main

func prin() int {
	fmt.Println("print")
	return 0
}

func demo() {
	defer func() {
		fmt.Println("1")
		recover()
	}()
        defer fmt.Println(recover(), prin())
	fmt.Println("before panic 2")
	panic(2)
}

func main() {
	demo()
}
```
Output:
>print
before panic 2
1 0
1

**Comment by Bububuger** [comment]
and if use `defer func() { ... }` , all action in func will be called in the exiting phase.

**Comment by go101** [comment]
This is explained at the end of the above mentioned article in Go 101.  The two `defer recover()` both try to recover panic 2, which are vain..

> What Go specification doesn't mention is that, at any given time, only the newest unrecovered panic in a goroutine is recoverable. In other words, each recover call is viewed as an attempt to recover the newest unrecovered panic in the currrent goroutine.

By the current explanations in Go specification, the first executed `recover()` should recover panic 1. This is a flaw in the current Go specification. 
* https://go-review.googlesource.com/c/go/+/189377
* https://github.com/golang/go/issues/34530

**Comment by Bububuger** [comment]
Thanks. It's inspiring me.

> That use of defer recover() in fuse is a bug, right? It is in effect a no-op.

I believe so.

_Originally posted by @mdempsky in https://github.com/golang/go/issues/34530#issuecomment-537640847_

I believe so, too

**Comment by TapirLiu** [comment]
It looks that all are clear now. I will close this issue in several days.

**Comment by go101** [comment]
I will close this issue soon.
