### ISSUE TITLE
Goexit with panic

### ISSUE THREAD

**Issue by bynil** [go101/go101#147]
In article https://go101.org/article/panic-and-recover-more.html

```
package main

import "runtime"

func f() {
	defer func() {
		recover()
	}()
	defer panic("will cancel Goexit but should not")
	runtime.Goexit()
}

func main() {
	c := make(chan struct{})
	go func() {
		defer close(c)
		f()
		for {
			runtime.Gosched()
		}
	}()
	<-c
}
```

> The following is another example neither gc nor gccgo compiles it correctly. The example program should exit quickly in running, but in fact it never exit if it is compiled with the current versions of gc and gccgo.

This example will exit since go1.14 `runtime.Goexit can no longer be aborted by a recursive panic/recover.` https://golang.org/doc/go1.14#pkg-runtime

**Comment by go101** [comment]
Aha, you are right. I though the issue https://github.com/golang/go/issues/29226 is still not closed so it might be not fixed yet.

Thanks for the correction!
