### ISSUE TITLE
Typos in Channel article

### ISSUE THREAD

**Issue by cerlestes** [go101/go101#15]
https://go101.org/article/channel.html

Channel Operations -> Point 4
Second word of citation should be "return".

> The rerurn value is an int value.

Channel Operations -> Point 5
Function should be "len", as mentioned in the line after the code block.
Also again, the article is talking of "rerurn values" :)

> cap(ch)
> The rerurn value is an int value.

Thanks for the wonderful articles!

**Comment by go101** [comment]
Thanks for the corrections.

btw, each "mentioned" also missed a "d". :)
