### ISSUE TITLE
Data Flow Manipulations suggestions

### ISSUE THREAD

**Issue by IbrahimMohammed47** [go101/go101#158]
The section (Concurrent Programming > Channel Use Cases > Data Flow Manipulations) is pretty interesting actually and I liked it very much, after reading it I thought about some changes and I wanted to know your opinion about it:

in the section, you provided 7 modules that can be composed together to form data pipelines, looking at the examples I found that the modules **Filter**, **Calculator**, take the output channels as parameters. 

I think it would be better to create the output channels from within the module functions because that way we can close the output channels in a cleaner way and at the right time.
so instead of this:
```
func Calculator(in <-chan uint64, out chan uint64) (<-chan uint64) {
	if out == nil {
		out = make(chan uint64)
	}
	go func() {
		for {
			x := <-in
			out <- ^x
		}
	}()
	return out
}
```
we can use this:
```
func Calculator(in <-chan uint64) (<-chan uint64) {
	out := make(chan uint64)
	go func() {
                for x := range in {
                     out <- ^x
                 }
                 close(out) 
	}()
	return out
}
```
I know you have stated that closing channels were not considered in the examples, but I think this issue affects our control over the channels and the way the functions are designed. 
I also think using `forrange` in most of this section examples is better because I'm not sure how the provided code examples can break out from the `for`'s.

I learned a lot from your book, and I am actually new to Go, so I'm sorry if I misunderstood anything, but I really want the best for this content. and I would really like to thank you for it.

**Comment by go101** [comment]
Before, the implementation of `Calculator` was written like you described.
Since some version, I added the second parameter for the last example.

> I also think using forrange in most of this section examples is better

It is true. Several examples can be rewritten with `for-range`.
I even just noticed a bug in the one example for not using `for-range`.
Thanks for the suggestion. I will modify some examples.
