### ISSUE TITLE
Pointers operator precedence correction

### ISSUE THREAD

**Issue by alexpashkov** [go101/go101#168]
Hi, I really enjoy your book, great work! I've found a small in the text, however. In the article on pointers it says:

`If p is a pointer to a numeric value, compilers will view *p++ is a legal statement and treat it as (*p)++. In other words, the precedence of the address-taken operator & and the pointer dereference operator * is higher than the increment operator ++ and decrement operator --.`

My concern is about & operator: It's actually illegal to write something like `&i++` or `&(i++)`. So it seems incorrect to say that the precedence of `&` operator is higher than `--`.

**Comment by go101** [comment]
@alexpashkov
You are totally right. I will modify it soon.
Thanks for this finding!
