### ISSUE TITLE
[basic-code-elements-introduction.html] A period is missing in line 258

### ISSUE THREAD

**Issue by baikai** [go101/go101#19]
A period is missing in line 258:
"There are some blank lines in the above program, to make the code get a better readability. And as this program is for code elements introduction purpose, there are many comments in it. Except the documentation comment for the StatRandomNumbers, other comments are for demostration purpose only We should try to make code self-explanatory and only use neccessary comments in formal projects."

**Comment by go101** [comment]
fixed.

Many thanks.
