### ISSUE TITLE
Wiki: remove redirect "The capacity of the result byte (or rune) slice of a conversion from a string is undefined"

### ISSUE THREAD

**Issue by janreggie** [go101/go101#197]
In [wiki:Unspecified behaviors in Go](https://github.com/go101/go101/wiki/Unspecified-behaviors-in-Go), the second bullet point points to the page [The capacity of the result byte (or rune) slice of a conversion from a string is undefined](https://github.com/go101/go101/wiki/The-capacity-of-the-result-byte-%28or-rune%29-slice-of-a-conversion-from-a-string-is-undefined), which is just a redirect to [The capacity of the result byte (or rune) slice of a conversion from a string is unspecified](https://github.com/go101/go101/wiki/The-capacity-of-the-result-byte-%28or-rune%29-slice-of-a-conversion-from-a-string-is-unspecified).

I am suggesting to remove the second page and replacing the link in the first page to the third one.

**Comment by go101** [comment]
Fixed. Thanks for this finding.

The second page will be kept to avoid breaking external links,
