### ISSUE TITLE
should it be "shift" or "unshift" when get the first element of the queue? 

### ISSUE THREAD

**Issue by zztczcx** [go101/go101#204]
I am reading the detailed explanation of channel, but this part is very confusing. 
from my understanding, 'shift' is to pop the first element of queue from head, 'unshift' is push an element to the head of queue.

> If the value buffer queue of the channel is not empty, in which case the receiving goroutine queue of the channel must be empty, the goroutine R will receive (by unshifting) a value from the value buffer queue. If the sending goroutine queue of the channel is also not empty, a sending goroutine will be unshifted out of the sending goroutine queue and resumed to running state again. The value the just unshifted sending goroutine trying to send will be pushed into the value buffer queue of the channel. The receiving goroutine R continues running. For this scenario, the channel receive operation is called a non-blocking operation.

R will receive (by `unshifting`) a value from the queue, and the sending goroutine will be `unshifted` out of the sending goroutine queue.

what is unshifted out of queue???

there is only shift out.

I want to confirm the usage of this word. 
If I am right I will make a pull request. 
Thanks

**Comment by go101** [comment]
Thanks very much!
Fixed now. No need to send PR.
