### ISSUE TITLE
About Underline In Packages Files

### ISSUE THREAD

**Issue by Sina-Ghaderi** [go101/go101#211]
The fact is if a file name start with _ (like _source.go) compiler does not recognized it as a go source file

Please mention this on "Code Packages and Package Imports" section.

**Comment by go101** [comment]
> a file name start with _ (like _source.go) compiler does not recognized it as a go source file

Okay, I will mention this, but in the "The Go Toolchain" article.

> a directory name starts with _ compiler doesn't care about content of this directory.

This doesn't look true.

**Comment by Sina-Ghaderi** [comment]
Yes, This doesn't apply for directories.. my bad.

**Comment by go101** [comment]
Fixed in https://github.com/go101/go101/commit/f0c2040d861930f238ed6660c7bad132be6e71e5
