### ISSUE TITLE
Should be leaves Mutex Locked

### ISSUE THREAD

**Issue by djimmo** [go101/go101#212]
Line 203 should state that function 2 leaves the mutex locked, instead of leaving the mutex unlocked right?

https://github.com/go101/go101/blob/a89360c683a2d22a41a1a152013332cb96475bdd/pages/fundamentals/defer-more.html#L203

```
var m sync.Mutex

func f1() {
	m.Lock()
	defer m.Unlock()
	doSomething()
}

func f2() {
	m.Lock()
	doSomething()
	m.Unlock()
}
```

**Comment by go101** [comment]
@djimmo 
Thanks for this finding.
It will be fixed soon.
