### ISSUE TITLE
typo in word

### ISSUE THREAD

**Issue by streamdp** [go101/go101#213]
Hey! Thanks for your great work!

Look you write **Normnalization**, but **Normalization** is more correct

https://github.com/go101/go101/blob/ee2b685cf19795b62527993c5fb068bf40bb98f2/pages/fundamentals/method.html#L626
https://github.com/go101/go101/blob/ee2b685cf19795b62527993c5fb068bf40bb98f2/pages/fundamentals/method.html#L663

**Comment by go101** [comment]
@streamdp
Thanks for this finding.
Will fix it soon.
