### ISSUE TITLE
Go Optimizations 101 (5.8 Use ballasts to avoid frequent GC cycles)

### ISSUE THREAD

**Issue by ivanburak** [go101/go101#219]
The link
![image](https://user-images.githubusercontent.com/64741656/153498527-d86c693b-b674-4892-a3d8-0f0ccfa281f8.png)
contains garbage symbols in its suffix

![image](https://user-images.githubusercontent.com/64741656/153498678-4a1223cf-8446-431a-bf4b-5ca0bedca8b8.png)

It should be
https://blog.twitch.tv/en/2019/04/10/go-memory-ballast-how-i-learnt-to-stop-worrying-and-love-the-heap/

**Comment by go101** [comment]
@ivanburak Thanks for the finding!
It will be fixed in the next release.

**Comment by go101** [comment]
It looks twitch changed the url, with a non-graceful way.
