### ISSUE TITLE
Do you mean incompatible types

### ISSUE THREAD

**Issue by Yousiph1** [go101/go101#220]
In the "type-system-overview" under "Types which support or Don't support comparisons"
There is this statement
 *Note, incomparable types are also called as incomparable types in many articles*
And wondering if it meant 
 *Note, incomparable types are also called incompatible types in many articles*

**Comment by go101** [comment]
Sorry, that should be `Note, incomparable types are also called uncomparable types in many articles.`
It will be fixed soon.

Thanks for this finding!
