### ISSUE TITLE
article: channel use cases

### ISSUE THREAD

**Issue by arsenalzp** [go101/go101#243]
Here is another human-transparent example about seats in a bar, with only one loop (except the last 'waiting' one) that allows server as many customers as possible however doesn't create  waste goroutines:

```
package main

import (
	"fmt"
	"math/rand"
	"time"
)

type Bar chan int

func (b Bar) ServerCustomer(c int) {
	fmt.Printf("customer # %v enter the bar\n", c)
	time.Sleep(time.Second * time.Duration(2+rand.Intn(6)))
	fmt.Printf("customer # %v left the bar\n", c)

         // free a seat for a next customer
	<-b 
}

func main() {
	rand.Seed(time.Now().UnixNano())
	b := make(Bar, 2)

	for i := 0; i <= 100; i++ {
                // reserve a seat for the customer
		b <- i
                // serve the customer
		go b.ServerCustomer(i)
	}

	for {
		time.Sleep(time.Second)
	}
}
```

**Comment by go101** [comment]
It looks it is the same as the manner mentioned in the code following the line `The manner of acquiring semaphore ownership through sending is simpler comparatively ...`

**Comment by arsenalzp** [comment]
Oh, I'm sorry for an inattentiveness!
