### ISSUE TITLE
Suggested definition for "reference type"

### ISSUE THREAD

**Issue by bobg** [go101/go101#246]
Regarding https://github.com/go101/go101/wiki/About-the-terminology-%22reference-type%22-in-Go:

The page is excellent, thanks for writing it. I have a suggestion for how to specify "reference type" more concretely: T is a reference type if a caller C can use a value of type T to make changes that will be visible outside of C's scope.

**Comment by go101** [comment]
@bobg 
I think that is a clear definition. But it needs to mention the following special notes

> * slice and reference array/struct types may present some non-reference type behaviors sometimes.
> * an interface value with a non-interface dynamic type presents non-reference type behaviors.

which makes explanations often not very clean and simple.

I do agree that sometimes the term "reference type" is useful in explaining things in Go.
But overall it will brings either confusions or explanation verbosity.

**Comment by bobg** [comment]
FWIW, I used my suggested definition (and linked to your page) in the documentation for [parallel.Protect](https://pkg.go.dev/github.com/bobg/go-generics/parallel#Protect).

**Comment by go101** [comment]
The definition is okay in that context. And that is a great Go lib.

I will close this issue. Discussion may continue if needed.
