### ISSUE TITLE
mistake in "Code Blocks and Identifier Scopes"

### ISSUE THREAD

**Issue by nekidb** [go101/go101#254]
I think there's mistake in this sentence:
"The scope of the identifier of a type of type alias declared inside a function body begins at the end of the identifier in the corresponding type specification and ends at the end of the innermost containing block. "

We can't use alias in the same specification of this alias. 
I think it should be like this:
"The scope of the identifier of a type declared inside a function body begins at the end of the identifier in the corresponding type specification and ends at the end of the innermost containing block. "

**Comment by go101** [comment]
It is true that `type T = *T` is invalid in Go, either the declaration is in the top package block or a local block.
The error message for such declarations is like `invalid recursive type: T refers to itself`, which in fact proves
the current description is right.

That is really a typo here: `of` should be `or`.

**Comment by nekidb** [comment]
But if "the scope of identifier of type alias begins at the end of the identifier in the corresponding type specification" then why I can't to this?

type T int
x := aT(10)
type aT = T

Maybe I don't fully understand this sentence, because I'm not good at English. By "corresponding type specification" it means the first line of code or last one?

**Comment by go101** [comment]
Your code contains two type specifications: `T int` and `aT = T`.
The use of `aT` is before the scope of `aT`, so the use is invalid.

```go
type T /* the scope of T starts here */ int
x := aT(10)
type aT /* the scope of aT starts here */ = T
```

**Comment by nekidb** [comment]
Current statement says: "The scope of the identifier of a type or a type alias declared inside a function body begins at the end of the identifier in the corresponding type specification and ends at the end of the innermost containing block"

So these two declarations have to be correct
```
type T1 struct {
    *T1
}

type T2 = struct {
    *T2
}
```

But last one says "invalid recursive type: T2 refers to itself". I think statement above is not correct for type alias.

**Comment by go101** [comment]
Your new example is the same as the old one. The message "invalid recursive type: T2 refers to itself" proves that the compiler thinks the second "T2" is exactly the first "T2". The compiler doesn't say "T2 is undefined", right? :)

**Comment by go101** [comment]
Maybe it is the difference between `theory scope` and `practical scope`. :)
