### ISSUE TITLE
Go Optimizations 101: 6-Map

### ISSUE THREAD

**Issue by zeisss** [go101/go101#256]
Link: https://go101.org/optimizations/6-map.html

Under "Clear map entries" it gives the following example to release a map:

```
aMap = map(map[K]V)
```

I think this is intended to be `aMap = make(map[K]V)`?

**Comment by go101** [comment]
@zeisss 
Thanks for finding this silly bug!

BTW, since Go 1.21, there is a better way to do this job: https://github.com/golang/go/issues/56351
