### ISSUE TITLE
More explanation needed in Channel chapter.

### ISSUE THREAD

**Issue by nofrish** [go101/go101#258]
In the "Channel Value Comparisons" of the  "Channel" chapter, the book writes:
"From the article value parts, we know that non-nil channel values are multi-part values. If one channel value is assigned to another, the two channels share the same underlying part(s). In other words, those two channels represent the same internal channel object. The result of comparing them is true."

I have a question, see the example below:
```
func main() {
	var ch1 = make(chan int)
	var ch2 chan<- int = ch1

	fmt.Printf("ch1: %T\n", ch1)
	fmt.Printf("ch2: %T\n", ch2)

	if ch1 == ch2 {
		println("ch1 == ch2")
	} else {
		println("ch1 != ch2")
	}
}
```

the weird thing is, `ch1` and `ch2` have different types, yet they can do comparison and they are even equal. I mean, they have different types.
can you please explain more here?

**Comment by go101** [comment]
The "Channel Types and Values" section mentions that

> Values of bidirectional channel type `chan T` can be implicitly converted to both send-only type `chan<- T` and receive-only type `<-chan T`, but not vice versa ...

In the comparison `ch1 == ch2`, `ch1` is implicitly converted the type of `ch2` before performing the comparison. It is equivalent to `(chan<- int)(ch1) == ch2`.

Please also read: https://go101.org/article/value-conversions-assignments-and-comparisons.html

**Comment by nofrish** [comment]
I understand. thank you.
