### ISSUE TITLE
typo in "concurrent-common-mistakes" about time.Timer's stop()

### ISSUE THREAD

**Issue by kuchaguangjie** [go101/go101#264]
url: https://go101.org/article/concurrent-common-mistakes.html
the part of typo:
> If the Stop method returns false, and we know the Timer value has not been stopped yet,

the `false` should be `true` I think.

**Comment by kuchaguangjie** [comment]
fix & PR: https://github.com/go101/go101/pull/265

**Comment by go101** [comment]
I re-read the doc: https://docs.go101.org/std/pkg/time.html#name-Timer and I think it is not a mistake.

Did you interpret

> If the Stop method returns false, and we know the Timer value has not been stopped yet, ...

as

> If the Stop method returns false, **then** we know the Timer value has not been stopped yet, ...

If yes, then I'm sorry, I think it should be improved as

> If we know the Timer value has not been stopped yet, and the Stop method returns false  ...

**Comment by kuchaguangjie** [comment]
ok, improve as you think is best, thx.
