### ISSUE TITLE
Value Conversion -  part 6 constants conversion rule - the explicitly cast is not required without type

### ISSUE THREAD

**Issue by kuchaguangjie** [go101/go101#266]
https://go101.org/article/value-conversions-assignments-and-comparisons.html

In these 2 lines the explicitly cast is not required without type:
```
	const F64b = float64(I3) // must be explicitly
	const I5 = int(C2) // must be explicitly
```

For demonstration, probably it should be written as:
```
	const F64b float64 = float64(I3) // must be explicitly
	const I5 int = int(C2)           // must be explicitly
```
Otherwise without explicitly cast it also works, like this:
```
	const F64b = I3
	const I5 = C2
```
Though the result will be of different type.

So, I think the rule is:
>  to cast constant value to a different type, need cast explicitly.

**Comment by go101** [comment]
@kuchaguangjie 
Thanks for creating this issue.

Some descriptions in this section are indeed inaccurate. I have just improved them a bit.
