### ISSUE TITLE
Pointer and unsafe pointer types should not be classified as "solo direct value parts"

### ISSUE THREAD

**Issue by minkj1992** [go101/go101#269]
- docs: https://go101.org/article/value-part.html

I found a potential mistake in the Go documentation regarding the classification of pointer types and unsafe pointer types as "solo direct value parts."

According to the documentation:

Types whose values each is only hosted on one single memory block (solo direct value part)

However, I believe this is inaccurate for pointer types and unsafe pointer types. In these cases, the value itself is not stored in a single memory block but rather split across multiple blocks.

<img width="774" alt="Screen Shot 2024-02-12 at 5 17 44 PM" src="https://github.com/go101/go101/assets/37536298/127093ff-cdd0-49f4-a581-7447806386fd">

**Comment by go101** [comment]
The value referenced by a pointer generally doesn't belong to the pointer.

**Comment by go101** [comment]
This issue will be closed soon. Comments can still be posted here if there are any questions.
