### ISSUE TITLE
Clarify the statement about memory allocation in C

### ISSUE THREAD

**Issue by minkj1992** [go101/go101#270]
- doc: https://go101.org/article/value-part.html

<img width="788" alt="Screen Shot 2024-02-12 at 6 20 16 PM" src="https://github.com/go101/go101/assets/37536298/8271fd72-fd79-4945-b03f-db77a3741901">

The statement "Each C value in memory occupies one memory block (one continuous memory segment)" in the document is not entirely accurate. While it is generally true for simple data types like integers and characters, it does not hold for more complex types like structs, arrays, and pointers.

For example, a struct can have members that are stored in different memory locations, a large array can span multiple blocks, and a pointer to a variable will be stored in a separate block from the variable itself.

I would suggest modifying the statement to focus on the memory allocation characteristics of simple types in C, such as integers and characters. Additionally, a note can be added to clarify that the memory layout of more complex types can be more intricate:

> The memory layout of C values depends on their type and complexity. Simple types like integers and characters occupy a single memory block, while more complex types like structs, arrays, and pointers can be spread across multiple blocks.

This change will provide a more accurate and nuanced understanding of memory allocation in C.

**Comment by go101** [comment]
> For example, a struct can have members that are stored in different memory locations, a large array can span multiple blocks, 

This is not true by my current knowledge.

> and a pointer to a variable will be stored in a separate block from the variable itself.

Yes, this is true (same as Go here). But the memory storing the pointer value itself is just a continuous segment.

**Comment by go101** [comment]
This issue will be closed soon. Comments can still be posted here if there are any questions.
