### ISSUE TITLE
how to make contributions to improve the readability of "Go Optimizations 101"

### ISSUE THREAD

**Issue by lpxz** [go101/go101#281]
Hi, thanks for this book Go Optimizations 101.

While I knew some patterns like the byte-slice-to-string allocation removal, I found lots of new patterns too, which are useful and inspiring. 

The book can be revised to make it more accessible to English readers, and I would be happy to do it. 

However, I found multiple chapters are marked "available in the paid ebook" (I bought it btw). Any suggestions?

**Comment by zigo101** [comment]
@lpxz 

Sorry for not notice this issue in time.

Thanks for supporting this book!

The "Go Optimizations 101" book project is now in a private repository.
I have sent an invitation to you.
