### ISSUE TITLE
Go optimization, slice growth

### ISSUE THREAD

**Issue by lpxz** [go101/go101#282]
func main() {
x1 := make([]int, 897)
x2 := make([]int, 1024)
y := make([]int, 100) println(cap(append(x1, y...))) println(cap(append(x2, y...)))
}

With Go toolchain v1.18+, the above example prints:
1360 1536
That is because Go 1.18 removes this drawback by tweaking the algorithm a bit:
var newcap int
var required = old.len + values.len if required > old.cap * 2 {
newcap = required } else {
const threshold = 256
if old.cap < threshold {
newcap = old.cap * 2 } else {
newcap = old.cap
for 0 < newcap && newcap < required {
                    newcap += (newcap + 3*threshold) / 4
               }
               // Avoid overflowing.
if newcap <= 0 { newcap = required
} }
}
Could you help understand why append(x2, y...) leads to cap=1536?

I got 1024+(1024+256*3)/4=1472, thanks

**Comment by zigo101** [comment]
In the 1.17 algorithm code, there is a line: 

> ... // Adjust memsize upwards to a nearby memory block class size.

Sorry, I omitted this lien for 1.18 code.

Here is the memory classes used currently: https://docs.go101.org/std/src/runtime/sizeclasses.go.html

**Comment by zigo101** [comment]
@lpxz I will close this issue. You can still continue the discussion if needed.
