### ISSUE TITLE
Deferred function calls should be pushed to a stack not to a queue like you have suggested under "Deferred Function calls".

### ISSUE THREAD

**Issue by balagrivine** [go101/go101#284]
Hello @zigo101;

Have a look at these paragraphs from Go 101 v1.23.b. The correct thing should be that deferred function calls are pushed to a stack not a queue.

When a defer statement is executed, the deferred function call is not executed immediately. Instead, it is pushed into a deferred call queue maintained by its caller goroutine. After a function call fc(...) returns (but has not fully exited yet) and enters its [exiting phase](https://go101.org/article/function-declarations-and-calls.html#exiting-phase), all the deferred function calls pushed into the deferred call queue during executing the function call will be removed from the deferred call queue and executed, in first-in, last-out order, that is, the reverse of the order in which they were pushed into the deferred call queue. Once all these deferred calls are executed, the function call fc(...) fully exits.

The arguments of a deferred function call are all evaluated at the moment when the corresponding defer statement is executed (a.k.a. when the deferred call is pushed into the deferred call queue). The evaluation results are used when the deferred call is executed later during the existing phase of the surrounding call (the caller of the deferred call).

Here is what Go documentation says: **Deferred function calls are pushed onto a stack. When a function returns, its deferred calls are executed in last-in-first-out order.**

Just  replace every instance of queue with stack, the remaining logic of LIFO is just fine.

Sorry if this issue had been raised earlier or if I'm reading an outdated version of the book.

**Comment by zigo101** [comment]
The word was "stack". To distinguish it from the normal call stack, I deliberately changed it to "queue". It is a FILO queue.

It looks "queue" often implies FIFO, right? How about "list"?

**Comment by balagrivine** [comment]
That still won't clear the ambiguity that arises. From a reader's perspective, I feel that the these corrections make it easy to understand. I have removed the "deferred call queue" statement and instead replaced it with only "stack"

When a defer statement is executed, the deferred function call is not executed immediately. Instead, it is pushed onto a stack maintained by its caller goroutine. After a function call fc(...) returns (but has not fully exited yet) and enters its [exiting phase](https://go101.org/article/function-declarations-and-calls.html#exiting-phase), all the deferred function calls pushed onto the stack during executing the function call will be removed from the stack and executed, in first-in, last-out order, that is, the reverse of the order in which they were pushed onto the queue. Once all these deferred calls are executed, the function call fc(...) fully exits.

The arguments of a deferred function call are all evaluated at the moment when the corresponding defer statement is executed (a.k.a. when the deferred call is pushed onto the stack). The evaluation results are used when the deferred call is executed later during the existing phase of the surrounding call (the caller of the deferred call).

Compare these with the previous paragraphs using "queue". I feel this brings much clarity to the reader since they won't have to grapple wondering why queue and LIFO are mentioned in the same sentence.

Feel free to get some thoughts from the rest of the community members too.

**Comment by zigo101** [comment]
I plan to change `deferred call queue` to `defer-call stack`. The term is also used in some other articles. A single word `stack` is not unique enough for all the articles.

**Comment by balagrivine** [comment]
Good, I'll be updating you frequently on areas that bring up ambiguity to the reader. Happy new year :)

**Comment by zigo101** [comment]
Happy new year.
