### ISSUE TITLE
May we translate your articles in go101.org?

### ISSUE THREAD

**Issue by oska874** [go101/go101#29]
Take the liberty to bother you.
We are volunteers of translation group from china and we are translating good technology articles from english to chinese. We found your articles in  
go101.org are very good. We want to translate  
you articles into chinese to make more chiese developpers and linuxers read  
it conveniencly . We will keep author and website information  
in translations. We will publish the articles in our website : linux.cn. 
Can we get your license?

**Comment by go101** [comment]
请参考这里的答复: https://github.com/go101/go101/issues/23

中文版由我本人维护.  以后License会放宽, 可以转载部分文章. 具体请参考后续的License修改.

这个issue先关闭了, 有问题可以继续跟帖. :)

**Comment by Cifer-Y** [comment]
I think if you accept and review others translation pull requests is much better than all by yourself.

**Comment by go101** [comment]
欢迎加入加入本书的中文翻译组 https://github.com/Golang101/golang101/issues/2
