### ISSUE TITLE
3.[keywords-and-identifiers.html] Don't use "mustn't " in formal article, use must not.

### ISSUE THREAD

**Issue by CHCP** [go101/go101#3]

**Comment by go101** [comment]
Looks, "must not" is more emphasis on the "not" than "mustn't", but both are legal. 
I will keep them unchanged for a period of time, unless some native English speakers mention this again.

**Comment by GoLangsam** [comment]
@go101 please consider to close!

**Comment by go101** [comment]
ok, this issue is closed.
