### ISSUE TITLE
Typo in "Introduction Of Source Code Elements" article

### ISSUE THREAD

**Issue by glebasterbajo** [go101/go101#36]
https://github.com/go101/go101/blob/c6e8a555cc6b368be3dbace0ec8475cc3cbc7b42/articles/basic-code-elements-introduction.html#L218

Line <i>1</i> specifies the package name of the currrent SOURCE (?) file.

**Comment by go101** [comment]
Yes, it is a typo.
In fact, there are more five such typos in other articles. :)

Thanks for submitting this issue.
