### ISSUE TITLE
Case of var []byte("Hello")

### ISSUE THREAD

**Issue by badu** [go101/go101#37]
On https://github.com/go101/go101/wiki/The-capacity-of-the-result-byte-%28or-rune%29-slice-of-a-conversion-from-a-string-is-undefined

var (
	h = []byte("Hello")
)

func main() {
	hc := append(h, " C"...)
	_ = append(h, " Go"...)
	fmt.Printf("%d, %d, %s\n", cap(h), len(h), hc)
}

prints the expected result of "hc". I think that this case should be analysed as well.

**Comment by go101** [comment]
cool finding!
Mentioned it in a new version of that wiki page.
