### ISSUE TITLE
4.[type-system-overview.html] "The sizes of the other types are compiler and architecture dependent."

### ISSUE THREAD

**Issue by CHCP** [go101/go101#4]
I think the statement "The sizes of the other types are compiler and architecture dependent." is not very preciseness, for example, size of int will be 32 or 64 dependence on architecture, but int32 always 32 bits on any architecture, and int64 always 64 bits.

**Comment by go101** [comment]
fixed in another article "basic-types-and-value-literals".
Thanks.
