### ISSUE TITLE
5.[basic-code-elements.html] "Package Load Order" give a example ,such as the follows.

### ISSUE THREAD

**Issue by CHCP** [go101/go101#5]
example for Package Load Order:
https://beego.me/docs/images/init.png

**Comment by go101** [comment]
The picture link is broken now.

This "Package Load Order" section is moved to "packages-and-imports" article.

It needs much efforts to explain the order in detail. Go 101 is a book focusing more on basic syntax, so this section will not be enhanced currently, unless more gophers make the same request later.
