### ISSUE TITLE
Typo[s]

### ISSUE THREAD

**Issue by wrfly** [go101/go101#53]
https://github.com/go101/go101/blob/a08fc0c3c37a4a8b326fdfcdf83f8552950d68f4/articles/channel.html#L1097

`solutuon`

I'll collect typos here and submit them in a single commit.

**Comment by go101** [comment]
Thanks for the finding.

BTW, do you mean you is preparing to submit a PR?

**Comment by wrfly** [comment]
Yes, I'm preparing for a PR. But you(or anyone else) can use this issue to correct the typos list here.
I just think it's a little improper for a commit only correct a single word.
We can update the docs weekly or make a PR with three or five typos at least .

**Comment by go101** [comment]
ok.

**Comment by wrfly** [comment]
https://github.com/go101/go101/blob/dcfd3600e3c1fa8db1cfb8396f1a163fed36b363/articles/details.html#L984
alway -> always

**Comment by go101** [comment]
acked.

**Comment by wrfly** [comment]
https://github.com/go101/go101/blob/dcfd3600e3c1fa8db1cfb8396f1a163fed36b363/articles/control-flows-more.html#L19-L20

> tons of thousand goroutines

> tens of thousands goroutines

**Comment by wrfly** [comment]
Or `if the function returns values` ?

**Comment by go101** [comment]
Not bad. 
Would `if the function returns any value` be a little better?

**Comment by go101** [comment]
modified (not committed yet).

**Comment by wrfly** [comment]
https://github.com/go101/go101/blob/dcfd3600e3c1fa8db1cfb8396f1a163fed36b363/articles/control-flows-more.html#L263

Operating system

**Comment by go101** [comment]
acked.

**Comment by wavvs** [comment]
https://github.com/go101/go101/blob/fb1e9c5e8b418996a38ef58016e4e64e8bd249ef/articles/introduction.html#L114
`versions`

https://github.com/go101/go101/blob/fb1e9c5e8b418996a38ef58016e4e64e8bd249ef/articles/introduction.html#L161
`languages`
https://github.com/go101/go101/blob/fb1e9c5e8b418996a38ef58016e4e64e8bd249ef/articles/introduction.html#L180
`really`

**Comment by go101** [comment]
acked.

**Comment by Jassob** [comment]
I added a line comment with my proposed edit, what do you think about it? 

https://github.com/go101/go101/commit/3c36898fa2e3b2de85494f6a29a21a2efa0190c8#r30158380

**Comment by go101** [comment]
@Jassob I replied your comments.

**Comment by bdaglish** [comment]
https://github.com/go101/go101/blob/74fe6b4e9e800722d084cc8a7bfe64cf930fbc93/articles/bounds-check-elimination.html#L279
`line 8 is also safe if line 7 is safe in function fc2.`

**Comment by go101** [comment]
@bdaglish 
thanks for the finding. 

In fact, it proved that "fc2" is also a mistake, it should be "fb2". And the next "fc1" should be "fc2". :)

**Comment by go101** [comment]
@bdaglish 
It would be great to create a new issue if you find other bugs later.
This thread is opend by wrfly.

**Comment by wens07** [comment]
https://github.com/go101/go101/blob/88fd46c1fa264d566d781154206b4469bcda9251/articles/packages-and-imports.html#L624

As i found the doc of Print,  does it mean if both not a string values. then it will add a space between them?

**Comment by wrfly** [comment]
@wens07 Indeed, if the arguments have the same type, then `Print` will insert a space between them.
See https://play.kfd.me/p/ultQ8XrUH4V

**Comment by go101** [comment]
@wens07 
Yes, "upport" is a typo.
And I missed a "not" in `If two consecutive arguments are both string values, ` It should be `If two consecutive arguments are both not string values,`.

Thanks for the mentions.

**Comment by wens07** [comment]
@go101 my pleasure and Thank you for this awesome project， it is very useful for new gopher like me.

**Comment by max-neverov** [comment]
hi,
not sure if there is something wrong, or just me not being able to understand:
https://github.com/go101/go101/blob/05791a65d0d290dda36a76ed9a7e1de812797382/articles/type-system-overview.html#L100
looks like an unfinished sentence to me.

https://github.com/go101/go101/blob/05791a65d0d290dda36a76ed9a7e1de812797382/articles/type-system-overview.html#L632-L633
should it be just `element type of a container type`?

**Comment by go101** [comment]
The first is a really grammar mistake. The second one is mainly caused by my not fluent English.
Fixed the first one and improve the second one.

Thanks for the findings!

**Comment by max-neverov** [comment]
thx for the book!

**Comment by xamenyap** [comment]
I found another grammar mistake [here](https://go101.org/article/type-system-overview.html)
> An interface type can **specified** zero or several methods, which form the method set of the interface type.

`specified` should be `specify`

**Comment by go101** [comment]
@xamenyap 
yes, it is a grammar mistake. 
Fixed now.
Thanks for pointing out this.

**Comment by go101** [comment]
I will close this issue, for this thread is originally prepared for @wrfly only.
But it looks people all think this is a typo collecting thread for all people. ;D
Everyone can still open a new issue or PR for all kinds of mistakes in this book.
