### ISSUE TITLE
question: Why must the receiving goroutine be empty if there are values in the buffer?

### ISSUE THREAD

**Issue by acpower7** [go101/go101#55]
sorry but don't know where else to ask.

I'm trying to understand this comment:

> At any time, if the value buffer is not empty, then its receiving goroutine queue must be empty.

Why must the receiving goroutine be empty if there are values in the buffer?? Isn't the point of the receiving goroutine to receive values from the buffer?

similarly: 

> At any time, if the value buffer is not full, then its sending goroutine queue must be empty.

thanks in advanced. 

[context:](https://go101.org/article/channel.html) 

> By the rules listed above, we can get some facts about the internal queues of a channel.
> If the channel is closed, both of its sending goroutine queue and receiving goroutine queue must be empty, but its value buffer queue may not be empty.
> At any time, if the value buffer is not empty, then its receiving goroutine queue must be empty.
> At any time, if the value buffer is not full, then its sending goroutine queue must be empty.
> If the channel is buffered, then at any time, one of its sending goroutine queue and receiving goroutine queue must be empty.
> If the channel is unbufferd, then at any time, generally one of its sending goroutine queue and the receiving goroutine queue must be empty, but with an exception that a goroutine may be pushed into both of the two queues when executing a select control flow code block.

**Comment by go101** [comment]
> At any time, if the value buffer is not empty, then its receiving goroutine queue must be empty.

If the value buffer (of a channel) is not empty, a receiving goroutine will succeed to receive a value from the channel. So the receiving goroutine will not be blocked in the receiving goroutine queue of the channel. (Please note, being a receiving goroutine of a channel doesn't mean the goroutine is in either queues of the channel.)

> At any time, if the value buffer is not full, then its sending goroutine queue must be empty.

Similar to the last answer. If the value buffer (of a channel) is not full, the a sending goroutine will push the sent value into the value bufffer, then continue to execute its following code without being blocked and being pushed into the sending goroutine queue of the channel.

**Comment by acpower7** [comment]
thanks for the clarification!
