### ISSUE TITLE
Would it be worth converting to Gitbook?

### ISSUE THREAD

**Issue by I-Dont-Remember** [go101/go101#6]
https://www.gitbook.com/ or something along those lines (such as a static site generator like hugo) so that content can be mostly separated from the HTML

**Comment by go101** [comment]
At the beginning of writing this book, I tried markdown.
But the presentation ability of markdown is a little weak, so I changed it to basic html.

Besides this book, there will be more contents hosted on go101.org, some of them may be interactive. So I think gitbook is not very good choice.

**Comment by go101** [comment]
I will closed the issue. You can still add comments below.

**Comment by GoLangsam** [comment]
@go101 - sorry to see this, but happy to find the information.
I am a happy user of markdown.
Please help me to see the page(s) of Yours where markdown would be too weak.
I started to use GitBook (legacy now) with a friend (a non-tech writer).
And I was initially confused seeing Your articles as html ...

**Comment by go101** [comment]
There will be some small articles on Go 101 github wiki.

For go101.org, there are a few things github and GitBook markdowns don't support well.
* custom header/footer
* markdown table tags are much harder to use than original html tags
* don't support custom javascript. Javascript may be required for some later contents on go101.org

**Comment by GoLangsam** [comment]
Hm...
- book: No need! :-) WebSite: Your server as well as e.g. pandoc would be happy to come to our rescue
- Yeah :-)
    - `basic-types-and-value-literals.html` has one,
    - `operators.html` has some (both easy & advanced), and
    - `summaries.html`
- Hm... future... wishful thinking ... to be kept in mind!
Anyway - this issues is closed, and shall remain so. I won't touch it again.
Alas: I look forward to share my three cents with You -  elsewhere. And another day :-)

**Comment by go101** [comment]
one more I missed: github and gitbook makrdown don't support line numbers in code.
