### ISSUE TITLE
A Use Case Of BCE: Efficient Slice Comparison section not true anymore

### ISSUE THREAD

**Issue by erikdubbelboer** [go101/go101#64]
The `A Use Case Of BCE: Efficient Slice Comparison` section on this page https://go101.org/article/bounds-check-elimination.html is not true anymore. The current version of Go (`1.11`) doesn't require this trick anymore and can removes the bounds check based on the `len()` comparison above.

Should this section maybe be removed from the page or should a warning be added that it's only relevant to older versions of Go?

**Comment by go101** [comment]
@erikdubbelboer 
thanks for pointing out this trick becomes obsoleted.
I added a note in that section and plan to remove it after some time.

**Comment by go101** [comment]
btw, you may need refresh that page to see the added note. The pages are cached for about 1.5 hours.
