### ISSUE TITLE
`unsafe.SizeOf()` returns a constant and can be used at compile time

### ISSUE THREAD

**Issue by deanveloper** [go101/go101#69]
See https://golang.org/ref/spec#Constants

This is in reference to "How to detect native word size at compile time?" under "Go Tips 101"

You can instead just do `unsafe.Sizeof(uint(0))*8`

**Comment by deanveloper** [comment]
this is issue #69 ayy

**Comment by go101** [comment]
Yes, it is true.
However, generally, Go 101 will try to avoid using the the unsafe ways in explanations, in particular if there are alternative ways. So this suggestion will not be adopted.

Thanks for this suggestion anyway.
