### ISSUE TITLE
How to force package users to use struct composite literals with field names?

### ISSUE THREAD

**Issue by Chyroc** [go101/go101#74]
https://go101.org/article/tips.html#force-to-use-keyed-struct-literals

```go
package main

import "fmt"

type Config struct {
	_    [0]int
	Name string
	Size int
}

func main() {
	fmt.Println(Config{[0]int{}, "bar", 123})
	fmt.Println(Config{Name: "bar", Size: 123})
}

```

```
go version
go version go1.11.1 darwin/amd64

{[] bar 123}
{[] bar 123}
```

**Comment by go101** [comment]
Yes, this tip doesn't work if the type declaration and its value literals are in the same package. In other words, the `Config` struct is expected to be declared in another package.

**Comment by go101** [comment]
close this issue now. You can still comment if you have any questions.
