### ISSUE TITLE
perfect clone slice and its cap

### ISSUE THREAD

**Issue by fasknifer** [go101/go101#79]
```
package main

import "fmt"

func CloneSlice(a []int) []int {
	return append(a[:0:0], a...)
}

func main() {
	a := make([]int, 3, 5)
	b := CloneSlice(a)
	fmt.Printf("cap of a is %v\n", cap(a))
	fmt.Printf("cap of b is %v\n", cap(b))
}
```

the result:
cap of a is 5
cap of b is 4

Is there a way to perfectly clone slice and its cap? (in short form)

A known but not short way:

```
func CloneSlice(a []int) []int {
	if nil == a {
		return nil
	}
	b := make([]int, len(a), cap(a))
	copy(b, a)
	return b
}
```

**Comment by go101** [comment]
Ah, I haven't found a way to clone a slice and assure the result slice has the same capacity with the cloned slice. But I have a way to assure the capacity of the result slice is larger than the cloned slice.
```golang
b := append(a[:0:0], a[:cap(a)]...)[:len(a)]
```
If you do want the capacity of the result slice is exactly the same as the cloned slice, then you can use the following line, though I recommend the above one over the following line, for the following line is some kind of memory leaking.
```golang
package main

import "fmt"

func main() {
	a := make([]int, 3, 5)
	b := append(a[:0:0], a[:cap(a)]...)[:len(a):cap(a)]
	fmt.Println(cap(a), len(a))
	fmt.Println(cap(b), len(a))
}
```

**Comment by go101** [comment]
You can continue to comment if you have more questions, otherwise, you can close it.
