### ISSUE TITLE
Boolean case compile dependent

### ISSUE THREAD

**Issue by darionyaphet** [go101/go101#80]
Hi : 
When I'm using **go version go1.11.2** to test **The numeric constant case expressions in a switch block can't be deplicate, but boolean ones can** example , found a compile error

```
switch false {
case false:	
case false:
}
```
It's looks like boolean case also make a `compile dependent`？

**Comment by go101** [comment]
Do you mean the code fails to compile?
It looks it compiles ok for me (go version go1.11.2 linux/amd64).

Yes, this behavior is compiler dependent, please view https://github.com/golang/go/issues/28357 for details.

**Comment by go101** [comment]
I will close this issue. You can comment more in this thread if you have more questions.
